CREATE DATABASE first_database;
CREATE DATABASE second_database;
USE second_database;
CREATE TABLE first_table();
CREATE TABLE second_table();
ALTER TABLE second_table ADD COLUMN first_column INT;
ALTER TABLE second_table ADD COLUMN id INT;
ALTER TABLE second_table ADD COLUMN age INT;
ALTER TABLE second_table DROP COLUMN age;
ALTER TABLE second_table DROP COLUMN first_column;
ALTER TABLE second_table ADD COLUMN name VARCHAR(30);
ALTER TABLE second_table RENAME COLUMN name TO username;
INSERT INTO second_table(id, username) VALUES (1, 'Samus');
SELECT * FROM second_table;
INSERT INTO second_table(id, username) VALUES (2, 'Mario');
INSERT INTO second_table(id, username) VALUES (3, 'Luigi');
DELETE FROM second_table WHERE username='Luigi';
DELETE FROM second_table WHERE username='Mario';
DELETE FROM second_table WHERE username='Samus';
ALTER TABLE second_table DROP COLUMN username;
ALTER TABLE second_table DROP COLUMN id;
DROP TABLE second_table;
ALTER DATABASE first_database RENAME TO mario_database;
ALTER TABLE characters ADD COLUMN name VARCHAR(30) NOT NULL;
ALTER TABLE characters ADD COLUMN homeland VARCHAR(60);
ALTER TABLE characters ADD COLUMN favorite_color VARCHAR(30);
INSERT INTO characters(character_id, name, homeland, favorite_color) VALUES (1, 'Mario', 'Mushroom Kingdom', 'Red');
INSERT INTO characters(character_id, name, homeland, favorite_color) VALUES (2, 'Luigi', 'Mushroom Kingdom', 'Green');
INSERT INTO characters(character_id, name, homeland, favorite_color) VALUES (3, 'Peach', 'Mushroom Kingdom', 'Pink');
INSERT INTO characters(character_id, name, homeland, favorite_color) VALUES (4, 'Toadstool', 'Mushroom Kingdom', 'Red'), (5, 'Bowser', 'Mushroom Kingdom', 'Green');
INSERT INTO characters(character_id, name, homeland, favorite_color) VALUES (6, 'Daisy', 'Sarasaland', 'Yellow'), (7, 'Yoshi', 'Dinosaur Land', 'Green');
UPDATE characters SET favorite_color='Orange' WHERE name='Daisy';
UPDATE characters SET name='Toad' WHERE favorite_color='Red';
UPDATE characters SET name='Mario' WHERE character_id = 1;
UPDATE characters SET favorite_color='Blue' WHERE name='Toad';
UPDATE characters SET favorite_color='Yellow' WHERE name='Bowser';
UPDATE characters SET homeland='Koopa Kingdom' WHERE name='Bowser';
SELECT * FROM characters ORDER BY character_id;
ALTER TABLE characters ADD PRIMARY KEY(name);
ALTER TABLE characters DROP CONSTRAINT characters_pkey;
ALTER TABLE characters ADD PRIMARY KEY(character_id);
CREATE TABLE more_info();
ALTER TABLE more_info ADD COLUMN more_info_id SERIAL;
ALTER TABLE more_info ADD PRIMARY KEY(more_info_id);
ALTER TABLE more_info ADD COLUMN birthday DATE;
ALTER TABLE more_info ADD COLUMN height INT;
ALTER TABLE more_info ADD COLUMN weight NUMERIC(4,1);
ALTER TABLE more_info ADD COLUMN character_id INT REFERENCES characters(character_id);
ALTER TABLE more_info ADD UNIQUE(character_id);
ALTER TABLE more_info ALTER COLUMN character_id SET NOT NULL;
SELECT character_id FROM characters;
SELECT character_id, name FROM characters;
INSERT INTO more_info (more_info_id, birthday, height, weight, character_id) VALUES (1, '1981-07-09', 155, 64.5, 1); 
